name: Daily Proxy Rules Merge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜 UTC 时间执行
  push:
    branches:
      - main  # 或者是您想要自动执行工作流的分支

permissions:
  contents: write

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 确保使用了正确的 token

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Merge Proxy Rules and Save to File
        run: python merge_proxy_rules.py

      - name: Commit and push merged rules file
        run: |
          git config --global user.name 'luyao'
          git config --global user.email 'l767475207@gmail.com'
          git add merged_rules.txt
          git commit -m 'Update merged proxy rules'
          git push
